version: '3'

tasks:
  install:
    aliases: [i]
    desc: Install cli tools
    cmds:
      - |
        cargo binstall \
          cargo-watch \
          cargo-udeps

  dev:
    desc: Watch and run
    cmds:
      - cargo watch -x "run {{.CLI_ARGS}}"

  udeps:
    aliases: [deps]
    desc: Find unused dependencies
    cmds:
      - cargo +nightly udeps